version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vixDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:6678@db:5432/vixDatabase

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
