services:
  - type: web
    name: db
    runtime: docker
    dockerfilePath: ./Dockerfile # здесь укажите путь к вашему Dockerfile для БД
    envVars:
      - key: POSTGRES_DB
        value: vixDatabase
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: 6678


  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile # здесь укажите путь к вашему Dockerfile для фронтенда
