version: 2

services:
- type: web
  name: backend
  env: docker
  context: backend
  envVars:
  - key: DATABASE_URL
    value: postgresql://postgres:6678@db:5432/vixDatabase

- type: web
  name: frontend
  env: docker
  context: frontend

databases:
- name: db
  type: postgres
